export interface IDailyProps {
    [key: string]: string;
  }
  export const dailyTasksJaneiro: IDailyProps = {
    "2023-01-01": "Inicie uma liquidação de verão, oferecendo descontos especiais em roupas leves e de praia.",
    "2023-01-02": "Promoção de conjuntos de roupas de ginástica e acessórios esportivos.",
    "2023-01-03": "Realize um desfile de moda online para mostrar as tendências de roupas do ano.",
    "2023-01-04": "Desconto em pijamas e roupas confortáveis para quem trabalha em casa.",
    "2023-01-05": "Lançamento de novas coleções de roupas para a temporada de primavera.",
    "2023-01-06": "Ofereça uma aula de estilo pessoal e combinação de roupas na loja ou virtualmente.",
    "2023-01-07": "Promoção de roupas feitas com materiais ecológicos e sustentáveis.",
    "2023-01-08": "Dia de descontos especiais para estudantes com apresentação de carteirinha.",
    "2023-01-09": "Destaque para roupas confortáveis e elegantes para o dia a dia.",
    "2023-01-10": "Promoção 'Leve 3, Pague 2' em acessórios de moda, como lenços e cintos.",
    "2023-01-11": "Realize um workshop sobre como montar um guarda-roupa versátil e funcional.",
    "2023-01-12": "Desconto especial em roupas de alta costura e peças exclusivas.",
    "2023-01-13": "Concurso de design de estampas de roupas nas redes sociais.",
    "2023-01-14": "Destaque para roupas personalizadas e sob medida.",
    "2023-01-15": "Desconto em produtos de cuidados e lavagem para prolongar a vida útil das roupas.",
    "2023-01-16": "Promoção para compras em atacado para revendedores de moda.",
    "2023-01-17": "Dê destaque a conjuntos de roupas para presentear em ocasiões especiais.",
    "2023-01-18": "Workshop sobre como organizar e manter um armário funcional e organizado.",
    "2023-01-19": "Desconto especial em roupas de festa e trajes formais.",
    "2023-01-20": "Promoção relâmpago em itens selecionados até o final do dia.",
    "2023-01-21": "Dê destaque a roupas vintage ou retrô e acessórios correspondentes.",
    "2023-01-22": "Promoção 'Compre um, Leve outro' em acessórios de moda, como chapéus e luvas.",
    "2023-01-23": "Desconto em cabides e organizadores para otimizar o espaço do guarda-roupa.",
    "2023-01-24": "Destaque para roupas de moda masculina e feminina de designers renomados.",
    "2023-01-25": "Liquidação de peças de coleções anteriores de marcas exclusivas.",
    "2023-01-26": "Desconto especial para compras online de roupas e acessórios.",
    "2023-01-27": "Ofereça embalagens de presente gratuitas para qualquer compra na loja.",
    "2023-01-28": "Promova os produtos mais vendidos do mês, incluindo as roupas mais populares.",
    "2023-01-29": "Desconto em uniformes e roupas escolares para preparação para volta às aulas.",
    "2023-01-30": "Workshop de estilo pessoal com ênfase na seleção de roupas adequadas.",
    "2023-01-31": "Anúncio de novas coleções de roupas que chegarão em fevereiro.",
};

export const dailyTasksFevereiro: IDailyProps = {
    "2023-02-01": "Lançamento de coleção especial para o Dia dos Namorados, com roupas e acessórios temáticos.",
    "2023-02-02": "Promoção de roupas vermelhas e rosas em celebração ao mês do amor.",
    "2023-02-03": "Desfile de moda com foco em looks românticos para o Dia dos Namorados.",
    "2023-02-04": "Desconto em presentes e acessórios, incentivando compras antecipadas para o Dia dos Namorados.",
    "2023-02-05": "Destaque para roupas com estampas e frases românticas para a data especial.",
    "2023-02-06": "Ofereça um brinde especial em compras acima de um determinado valor.",
    "2023-02-07": "Realize um workshop de estilo e combinações de roupas para casais.",
    "2023-02-08": "Desconto em roupas de luxo e alta costura para ocasiões especiais.",
    "2023-02-09": "Ofereça personalização gratuita em peças selecionadas de roupas e acessórios.",
    "2023-02-10": "Promoção 'Compre um, Ganhe desconto no segundo' em itens de moda e acessórios.",
    "2023-02-11": "Sugira ideias de presentes criativos e elegantes para o Dia dos Namorados.",
    "2023-02-12": "Desconto em conjuntos de roupas combinando para casais com estilo.",
    "2023-02-13": "Ofereça entrega expressa gratuita para compras de última hora do Dia dos Namorados.",
    "2023-02-14": "Celebre o Dia dos Namorados com eventos especiais e descontos em roupas e acessórios.",
    "2023-02-15": "Incentive os clientes a deixarem feedbacks sobre as roupas e acessórios adquiridos para o Dia dos Namorados.",
    "2023-02-16": "Promoção em itens de moda relacionados ao retorno às aulas e à estação de outono.",
    "2023-02-17": "Destaque para roupas escolares ecológicas e materiais sustentáveis para estudantes.",
    "2023-02-18": "Workshop sobre tendências de moda para estudantes, com foco em como usar peças de roupa na escola.",
    "2023-02-19": "Promova roupas e acessórios que ajudam na organização e produtividade dos estudantes.",
    "2023-02-20": "Desconto em mochilas e acessórios escolares de marcas renomadas.",
    "2023-02-21": "Ofereça conjuntos de roupas escolares personalizados para diferentes faixas etárias e preferências de estilo.",
    "2023-02-22": "Promova roupas de arte e design para estudantes de moda e artes, com descontos especiais.",
    "2023-02-23": "Desconto em roupas e acessórios para professores, reconhecendo seu papel na comunidade escolar.",
    "2023-02-24": "Promoção 'Leve 3, Pague 2' em peças de vestuário de diferentes estilos e marcas.",
    "2023-02-25": "Incentive a compra de roupas sustentáveis oferecendo um brinde ecológico exclusivo.",
    "2023-02-26": "Promova um concurso de design de moda com premiações em roupas e acessórios exclusivos.",
    "2023-02-27": "Destaque para as últimas tendências da moda que acabaram de chegar em sua loja.",
    "2023-02-28": "Liquidação de fim de mês com prévia das novas coleções que chegarão em março.",
};

export const dailyTasksMarco: IDailyProps = {
    "2023-03-01": "Apresente a nova coleção de roupas para a primavera e incentive os clientes a renovarem seus guarda-roupas.",
    "2023-03-02": "Realize uma sessão de perguntas e respostas nas redes sociais sobre as últimas tendências de moda.",
    "2023-03-03": "Destaque as peças mais vendidas da semana passada com descontos especiais.",
    "2023-03-04": "Organize um workshop de estilo e combinações de roupas, demonstrando diferentes looks usando produtos da sua loja.",
    "2023-03-05": "Ofereça brindes exclusivos em compras acima de um determinado valor para estimular mais vendas.",
    "2023-03-06": "Realize uma venda relâmpago de 24 horas em uma seleção de roupas e acessórios.",
    "2023-03-07": "Lance um programa de fidelidade para incentivar os clientes a retornarem e comprarem mais roupas.",
    "2023-03-08": "Comemore o Dia Internacional da Mulher com ofertas especiais em roupas femininas e destaque as mulheres empreendedoras na indústria da moda.",
    "2023-03-09": "Promova um concurso de desfile de moda infantil com prêmios emocionantes para as crianças participantes.",
    "2023-03-10": "Realize um novo workshop virtual sobre dicas de estilo e combinações de roupas usando seus produtos de moda.",
    "2023-03-11": "Ofereça descontos em peças de roupas essenciais, como camisetas e calças, para incentivar a renovação do guarda-roupa.",
    "2023-03-12": "Promova uma venda de fim de semana com descontos especiais em toda a loja de roupas.",
    "2023-03-13": "Incentive os clientes a deixarem avaliações e feedbacks positivos sobre as roupas adquiridas nas redes sociais e no site.",
    "2023-03-14": "Destaque as peças mais vendidas da semana anterior com descontos especiais para clientes fiéis.",
    "2023-03-15": "Realize uma promoção de meio de março! Ofereça descontos em produtos selecionados e divulgue nas redes sociais.",
    "2023-03-16": "Promova uma sessão de autógrafos virtual com um influenciador de moda ou designer de roupas renomado.",
    "2023-03-17": "Lance uma linha de roupas temáticas de primavera, incluindo estampas florais e cores vibrantes.",
    "2023-03-18": "Realize uma promoção de Páscoa com descontos em roupas e acessórios primaverais.",
    "2023-03-19": "Organize um desfile de moda comunitário ao ar livre para celebrar a chegada da primavera.",
    "2023-03-20": "Celebre o Dia Mundial da Felicidade oferecendo descontos especiais em roupas coloridas e alegres.",
    "2023-03-21": "Apresente novos designs de roupas para a primavera, incluindo peças leves e elegantes para a estação.",
    "2023-03-22": "Destaque suas melhores peças de roupa de alta qualidade, oferecendo descontos exclusivos aos clientes.",
    "2023-03-23": "Realize uma pesquisa nas redes sociais para coletar sugestões de estilos e peças favoritas dos clientes.",
    "2023-03-24": "Promova uma venda-relâmpago de 12 horas em itens de moda favoritos dos clientes, incentivando compras rápidas.",
    "2023-03-25": "Realize um sorteio nas redes sociais com um grande prêmio, como um conjunto completo de roupas de sua loja.",
    "2023-03-26": "Ofereça frete grátis em compras acima de um determinado valor durante o fim de semana de primavera.",
    "2023-03-27": "Incentive os clientes a compartilharem fotos de seus looks com roupas da sua loja usando uma hashtag exclusiva.",
    "2023-03-28": "Destaque roupas premium e de alta qualidade, oferecendo uma promoção exclusiva de 'Compre 1, Leve 1' para peças selecionadas.",
    "2023-03-29": "Lance uma linha de roupas de jardinagem para a primavera, incluindo roupas leves e práticas para atividades ao ar livre.",
    "2023-03-30": "Promova uma venda de limpeza de estoque para liberar espaço para as novas coleções de roupas da próxima estação.",
    "2023-03-31": "Termine o mês revisando seu inventário de roupas e planejando promoções e eventos para o próximo mês de abril.",
};

export const dailyTasksAbril: IDailyProps = {
    "2023-04-01": "Celebre o Dia da Mentira com roupas divertidas e ousadas! Ofereça descontos em peças de vestuário com estampas e designs engraçados.",
    "2023-04-02": "Realize uma sessão de brainstorming online para coletar ideias de design e estilos de roupas dos clientes.",
    "2023-04-03": "Lance uma nova coleção de roupas temáticas para a primavera, com cores vibrantes e estampas florais.",
    "2023-04-04": "Realize uma venda-relâmpago para produtos específicos e limite-a às primeiras 50 compras.",
    "2023-04-05": "Colabore com um influenciador digital local para promover suas roupas em suas redes sociais e eventos.",
    "2023-04-06": "Ofereça descontos em roupas eco-friendly em comemoração ao Dia da Terra.",
    "2023-04-07": "Lance uma campanha de marketing digital focada em destacar sua coleção de roupas sustentáveis e ecologicamente corretas.",
    "2023-04-08": "Ofereça uma promoção especial para o Dia Internacional do Desenho com descontos em roupas confortáveis e adequadas para desenhar.",
    "2023-04-09": "Realize uma competição de design de moda online para estilistas locais com prêmios emocionantes.",
    "2023-04-10": "Promova roupas relacionadas a viagens e aventuras para as férias da primavera, incluindo roupas confortáveis e funcionais.",
    "2023-04-11": "Ofereça descontos em roupas de viagem e conjuntos de roupas versáteis para planejamento de viagens.",
    "2023-04-12": "Incentive os clientes a compartilharem histórias de suas aventuras usando roupas de sua loja nas redes sociais.",
    "2023-04-13": "Destaque conjuntos de roupas adequados para viagens, incluindo roupas leves, versáteis e fáceis de dobrar.",
    "2023-04-14": "Realize uma venda-relâmpago em itens de moda selecionados, limitado às primeiras 100 compras.",
    "2023-04-15": "Promova roupas e conjuntos de arte para crianças, incentivando a criatividade e expressão artística durante as férias.",
    "2023-04-16": "Ofereça um workshop virtual sobre estilo e combinações de roupas para diferentes tipos de viagem e aventura.",
    "2023-04-17": "Destaque os mais novos designs de roupas de primavera, incluindo estampas florais e tecidos leves para a estação.",
    "2023-04-18": "Promova uma venda especial de 'Meio do Mês' com descontos em roupas selecionadas para clientes fiéis.",
    "2023-04-19": "Ofereça descontos especiais para clientes que trouxerem roupas usadas para reciclagem, promovendo práticas de moda sustentáveis.",
    "2023-04-20": "Celebre o Dia da Terra com descontos em roupas ecológicas e sustentáveis, destacando materiais orgânicos e processos de produção responsáveis.",
    "2023-04-21": "Incentive os clientes a participarem de atividades de plantio de árvores ao comprar produtos específicos, promovendo práticas de sustentabilidade.",
    "2023-04-22": "Lance uma nova linha de roupas em colaboração com uma marca de moda ecológica, destacando a importância da moda sustentável.",
    "2023-04-23": "Ofereça descontos em roupas temáticas de jardinagem e natureza, promovendo um estilo de vida ao ar livre e conectado com a natureza.",
    "2023-04-24": "Promova uma venda-relâmpago de fim de semana para limpar estoques de roupas antes da chegada das novas coleções de primavera.",
    "2023-04-25": "Lance uma linha de roupas feitas com materiais reciclados, demonstrando seu compromisso com a moda sustentável e a redução de resíduos.",
    "2023-04-26": "Destaque roupas e estilos inspirados na natureza, como estampas florais e materiais orgânicos para uma moda consciente e ecológica.",
    "2023-04-27": "Ofereça um workshop sobre práticas sustentáveis na indústria da moda, promovendo o consumo consciente e ético de roupas.",
    "2023-04-28": "Promova uma venda-relâmpago de fim de semana para liberar espaço para as novas coleções de roupas de verão que chegarão em breve.",
    "2023-04-29": "Incentive os clientes a escreverem cartas manuscritas para amigos e familiares, promovendo a conexão pessoal e a expressão emocional.",
    "2023-04-30": "Finalize o mês com uma revisão das vendas de roupas e planeje eventos e promoções emocionantes para o próximo mês de maio.",
};

export const dailyTasksMaio: IDailyProps = {
    "2023-05-01": "Celebre o Dia do Trabalho com descontos especiais em roupas de trabalho e itens de moda profissional. Destaque peças de vestuário que agregam estilo e funcionalidade ao ambiente de trabalho.",
    "2023-05-02": "Lance novos designs de roupas com temas de primavera e verão, incluindo estampas vibrantes e tecidos leves para a temporada.",
    "2023-05-03": "Realize uma sessão de perguntas e respostas online sobre tendências de moda e estilo de trabalho, fornecendo dicas valiosas para os clientes.",
    "2023-05-04": "Promova uma 'Semana da Gratidão', incentivando os clientes a apreciarem seus colegas de trabalho e entes queridos com gestos de gratidão e presentes simbólicos.",
    "2023-05-05": "Celebre o Cinco de Mayo com descontos especiais em roupas coloridas e acessórios festivos para o ambiente de trabalho.",
    "2023-05-06": "Ofereça workshops de estilo e moda para profissionais, fornecendo dicas práticas de vestuário e acessórios para o local de trabalho.",
    "2023-05-07": "Promova uma venda de domingo com descontos especiais em peças de vestuário e acessórios selecionados.",
    "2023-05-08": "Destaque produtos relacionados à arte e criatividade para o ambiente de trabalho, como acessórios elegantes e confortáveis para profissionais criativos.",
    "2023-05-09": "Promova uma campanha de mídia social destacando a importância da moda no ambiente profissional e as melhores práticas de vestimenta para o sucesso no trabalho.",
    "2023-05-10": "Ofereça um brinde especial nas compras acima de um valor determinado para celebrar o Dia das Mães e reconhecer as mães que são profissionais.",
    "2023-05-11": "Promova um concurso nas redes sociais onde os clientes podem ganhar um kit de roupas profissionais para presentear no Dia das Mães.",
    "2023-05-12": "Lance produtos personalizados perfeitos para presentes do Dia das Mães, incluindo roupas elegantes e acessórios sofisticados para mães profissionais.",
    "2023-05-13": "Ofereça embalagens de presente gratuitas para qualquer compra relacionada ao Dia das Mães, fornecendo um serviço adicional para os clientes.",
    "2023-05-14": "Celebre o Dia das Mães destacando histórias inspiradoras de mães que alcançaram sucesso em suas carreiras profissionais.",
    "2023-05-15": "Inicie uma promoção de meados de mês com descontos especiais em roupas e acessórios selecionados para profissionais.",
    "2023-05-16": "Promova produtos sustentáveis e eco-friendly para o ambiente de trabalho, destacando roupas feitas com materiais reciclados e sustentáveis.",
    "2023-05-17": "Lance um programa de reciclagem de roupas na loja, incentivando os clientes a doarem roupas usadas para instituições de caridade locais.",
    "2023-05-18": "Destaque os benefícios de roupas eco-friendly e sustentáveis para o ambiente de trabalho, promovendo um estilo de vida consciente e responsável.",
    "2023-05-19": "Organize um evento local de troca de roupas profissionais e acessórios de trabalho, promovendo a reutilização e sustentabilidade na moda.",
    "2023-05-20": "Promova um desconto especial para estudantes que estão se preparando para entrevistas de emprego e necessitam de roupas adequadas para o ambiente profissional.",
    "2023-05-21": "Colabore com designers locais para criar coleções exclusivas de roupas profissionais, destacando a diversidade e criatividade na moda para o trabalho.",
    "2023-05-22": "Promova uma venda-relâmpago de 48 horas em itens de moda profissional, fornecendo oportunidades exclusivas de compra para os clientes.",
    "2023-05-23": "Incentive os clientes a compartilharem seus looks profissionais nas redes sociais, promovendo a moda e o estilo no ambiente de trabalho.",
    "2023-05-24": "Ofereça tutoriais em vídeo sobre dicas de estilo e vestimenta profissional, fornecendo orientações práticas para os clientes.",
    "2023-05-25": "Promova uma venda especial de 'Final de Mês' com descontos em peças de vestuário e acessórios populares para o ambiente de trabalho.",
    "2023-05-26": "Realize um evento de apreciação do cliente com ofertas especiais e oportunidades de networking para profissionais locais na loja.",
    "2023-05-27": "Ofereça frete grátis para compras online durante o fim de semana, incentivando os clientes a explorarem a coleção online de roupas profissionais.",
    "2023-05-28": "Celebre o Dia Mundial do Brincar destacando roupas confortáveis e elegantes para crianças, promovendo o estilo e a diversão na moda infantil.",
    "2023-05-29": "Lance uma nova linha de roupas exclusivas para o verão, incluindo peças leves e coloridas para os dias quentes.",
    "2023-05-30": "Ofereça uma promoção 'Compre 1, Leve 1 Grátis' em roupas selecionadas, proporcionando uma oportunidade única de compra para os clientes.",
    "2023-05-31": "Encerre o mês agradecendo aos clientes leais e profissionais por seu apoio contínuo, demonstrando apreço pela comunidade profissional e empresarial.",
};
export const dailyTasksJunho: IDailyProps = {
    "2023-06-01": "Destaque a nova coleção de verão, exibindo roupas leves e coloridas perfeitas para os dias quentes.",
    "2023-06-02": "Ofereça descontos especiais em trajes de banho e acessórios de verão para incentivar os clientes a se prepararem para a temporada de praia.",
    "2023-06-03": "Realize um desfile de moda ao ar livre para apresentar as tendências da estação, atraindo entusiastas da moda e clientes em potencial.",
    "2023-06-04": "Lance uma promoção 'Compre 1, Leve 1 com Desconto' para encorajar os clientes a experimentarem novos estilos e combinações de roupas.",
    "2023-06-05": "No Dia Mundial do Meio Ambiente, destaque roupas ecológicas e sustentáveis, enfatizando materiais reciclados e práticas de produção sustentáveis na indústria da moda.",
    "2023-06-06": "Colabore com influenciadores de moda para um evento de styling ao vivo, demonstrando diferentes maneiras de combinar peças de roupa para ocasiões variadas.",
    "2023-06-07": "Promova roupas confortáveis e estilosas para atividades ao ar livre, como caminhadas e piqueniques, destacando materiais leves e respiráveis.",
    "2023-06-08": "Ofereça consultas de estilo personalizadas na loja para ajudar os clientes a descobrirem seu próprio estilo e a escolherem roupas que realcem sua individualidade.",
    "2023-06-09": "Realize um evento de troca de roupas usadas para promover práticas de consumo consciente e sustentável, incentivando os clientes a doarem roupas em bom estado.",
    "2023-06-10": "Apresente uma nova linha de roupas de ginástica e sportswear, incentivando um estilo de vida ativo e saudável entre os clientes.",
    "2023-06-11": "Promova descontos especiais em roupas para ocasiões especiais, como vestidos de festa e trajes elegantes, para clientes que estão se preparando para eventos importantes.",
    "2023-06-12": "Crie uma promoção especial para o Dia dos Namorados, oferecendo descontos em conjuntos de roupas e acessórios para casais.",
    "2023-06-13": "Organize um desfile de moda infantil para apresentar as últimas tendências em roupas para crianças, atraindo pais e famílias interessados em moda infantil.",
    "2023-06-14": "Ofereça descontos exclusivos em roupas casuais para o dia a dia, incentivando os clientes a renovarem seus guarda-roupas com peças confortáveis e versáteis.",
    "2023-06-15": "Lance um programa de fidelidade para clientes frequentes, oferecendo pontos de recompensa para cada compra de roupa e acessórios na loja.",
    "2023-06-16": "Promova uma venda 'Leve 3, Pague 2' em peças selecionadas, incentivando os clientes a experimentarem novos estilos e combinações de roupas.",
    "2023-06-17": "Ofereça brindes exclusivos, como lenços ou acessórios, para compras acima de um valor determinado, proporcionando um incentivo adicional para os clientes.",
    "2023-06-18": "Organize um evento de moda masculina para destacar as últimas tendências em roupas e acessórios para homens, atraindo um público interessado em moda masculina.",
    "2023-06-19": "Destaque roupas versáteis e práticas para o dia a dia, como peças que podem ser facilmente combinadas e usadas em diferentes ocasiões.",
    "2023-06-20": "Promova presentes de roupas exclusivos para o Dia dos Pais, oferecendo opções elegantes e personalizadas para presentear os pais.",
    "2023-06-21": "Celebre o primeiro dia do inverno com uma promoção especial em roupas e acessórios de inverno, destacando peças quentes e estilosas.",
    "2023-06-22": "Lance uma linha de roupas com estampas e designs inspirados na natureza e no ambiente tropical, oferecendo opções únicas e vibrantes.",
    "2023-06-23": "Apresente descontos especiais para estudantes em busca de roupas novas para o próximo ano letivo, promovendo uma variedade de estilos adequados para a escola.",
    "2023-06-24": "Promova um concurso de moda nas redes sociais, encorajando os clientes a compartilharem seus looks favoritos usando roupas da sua loja.",
    "2023-06-25": "Ofereça um workshop sobre cuidados com as roupas e dicas de lavagem para ajudar os clientes a manterem suas roupas em bom estado por mais tempo.",
    "2023-06-26": "Inicie uma liquidação de fim de mês com descontos atrativos em uma ampla seleção de roupas, incentivando os clientes a aproveitarem as ofertas finais do mês.",
    "2023-06-27": "Promova uma 'Semana de Apreciação do Cliente' com descontos exclusivos e benefícios especiais para demonstrar gratidão pela lealdade dos clientes.",
    "2023-06-28": "Ofereça serviços de ajuste e customização de roupas para garantir que os clientes tenham peças que se ajustem perfeitamente às suas preferências e necessidades.",
    "2023-06-29": "Destaque uma coleção de roupas inspiradas em destinos de viagem famosos, oferecendo opções elegantes e confortáveis para os entusiastas de viagens.",
    "2023-06-30": "Agradeça aos seus clientes pelo apoio contínuo e dê uma prévia das promoções e eventos planejados para o próximo mês."
};

export const dailyTasksJulho: IDailyProps = {
    "2023-07-01": "Lance uma nova coleção de verão com roupas leves e coloridas, perfeitas para os dias quentes.",
    "2023-07-02": "Promova um desfile de moda com modelos da comunidade local usando suas roupas favoritas da loja.",
    "2023-07-03": "Organize uma venda de roupas de banho e acessórios de verão para incentivar os clientes a se prepararem para a temporada de férias.",
    "2023-07-04": "Celebre o feriado com descontos especiais em roupas festivas e acessórios temáticos.",
    "2023-07-05": "Realize um concurso de moda online, incentivando os clientes a compartilharem suas melhores combinações de roupas de verão.",
    "2023-07-06": "Ofereça um desconto especial em itens de proteção solar, como chapéus e óculos de sol, para promover a conscientização sobre a proteção contra os raios UV.",
    "2023-07-07": "Promova uma venda de fim de semana com descontos exclusivos em roupas esportivas e de lazer.",
    "2023-07-08": "Lance uma linha exclusiva de roupas de dormir confortáveis e elegantes.",
    "2023-07-09": "Realize uma sessão de estilo pessoal, oferecendo consultoria de moda gratuita aos clientes.",
    "2023-07-10": "Ofereça workshops de costura para iniciantes, ensinando técnicas básicas de ajuste e customização de roupas.",
    "2023-07-11": "Lance uma promoção 'Volta ao Trabalho' com descontos em roupas formais e elegantes para o escritório.",
    "2023-07-12": "Inicie uma campanha de doação de roupas para instituições de caridade locais.",
    "2023-07-13": "Ofereça um desconto em acessórios de moda, como bolsas e lenços, para complementar os visuais dos clientes.",
    "2023-07-14": "Promova um evento de troca de roupas usadas, incentivando os clientes a adotarem práticas de moda sustentável.",
    "2023-07-15": "Lance uma nova linha de roupas casuais elegantes, perfeitas para ocasiões especiais e encontros informais.",
    "2023-07-16": "Ofereça um brinde exclusivo na compra de um conjunto completo de roupas.",
    "2023-07-17": "Apresente uma coleção de roupas de marca de luxo, destacando designs exclusivos e materiais de alta qualidade.",
    "2023-07-18": "Lance uma oferta especial para roupas infantis e acessórios para crianças.",
    "2023-07-19": "Organize um desfile de moda infantil, exibindo as últimas tendências em roupas para crianças.",
    "2023-07-20": "Promova uma venda-relâmpago de roupas de marca renomada a preços acessíveis por tempo limitado.",
    "2023-07-21": "Ofereça descontos especiais em roupas de festa e trajes formais.",
    "2023-07-22": "Apresente uma nova linha de roupas esportivas, incentivando um estilo de vida ativo e saudável.",
    "2023-07-23": "Realize um evento de moda inclusiva, celebrando a diversidade de tamanhos e estilos.",
    "2023-07-24": "Destaque os produtos mais vendidos do mês e ofereça pacotes promocionais em conjuntos de roupas.",
    "2023-07-25": "Incentive os clientes a deixarem avaliações e feedbacks online sobre suas experiências de compra de roupas.",
    "2023-07-26": "Ofereça tutoriais de estilo e dicas de moda em vídeo para inspirar os clientes a experimentarem novos looks.",
    "2023-07-27": "Promova uma venda de roupas de inverno antecipada, oferecendo descontos em casacos e acessórios quentes.",
    "2023-07-28": "Lance uma linha de roupas ecológicas e sustentáveis, utilizando materiais reciclados e processos de produção sustentáveis.",
    "2023-07-29": "Realize uma promoção de encerramento de mês com descontos em toda a loja, incluindo uma variedade de roupas e acessórios.",
    "2023-07-30": "Organize um desfile de moda de encerramento de mês, apresentando os looks mais populares e elegantes do mês.",
    "2023-07-31": "Encerre o mês com um evento de agradecimento aos clientes, oferecendo descontos especiais e brindes exclusivos como forma de reconhecer a lealdade dos clientes."
  };
  export const dailyTasksAgosto: IDailyProps = {
    "2023-08-01": "Apresente a nova coleção de verão, exibindo roupas leves e coloridas perfeitas para os dias quentes de agosto.",
    "2023-08-02": "Destaque as últimas tendências em roupas escolares para estudantes de todas as idades, oferecendo opções estilosas e confortáveis.",
    "2023-08-03": "Organize um desfile de moda de volta às aulas, apresentando diferentes looks adequados para o ambiente escolar.",
    "2023-08-04": "Promova uma venda especial de roupas universitárias, oferecendo descontos em estilos adequados para estudantes universitários.",
    "2023-08-05": "Realize um evento de moda ao ar livre para estudantes, apresentando as últimas tendências em roupas e acessórios para a nova temporada escolar.",
    "2023-08-06": "Colabore com influenciadores de moda para um desafio de styling estudantil nas redes sociais, incentivando os alunos a mostrarem seus looks favoritos para a escola.",
    "2023-08-07": "Ofereça descontos especiais em roupas escolares online durante a primeira semana de agosto, facilitando as compras para os alunos e seus pais.",
    "2023-08-08": "Lance um programa de fidelidade para estudantes, fornecendo benefícios exclusivos, descontos e ofertas especiais para clientes frequentes.",
    "2023-08-09": "Realize um webinar sobre as últimas tendências em moda escolar, fornecendo dicas e orientações para os alunos escolherem o melhor estilo para o novo ano letivo.",
    "2023-08-10": "Promova descontos em mochilas, sapatos e acessórios escolares, incentivando os alunos a se prepararem completamente para o início das aulas.",
    "2023-08-11": "Destaque a importância de roupas confortáveis e práticas para um dia inteiro de estudos, incentivando os alunos a escolherem roupas adequadas para longas horas na escola.",
    "2023-08-12": "Ofereça um workshop de moda escolar, demonstrando diferentes maneiras de combinar roupas e acessórios para um estilo escolar único e pessoal.",
    "2023-08-13": "Promova uma venda especial para compras em grande quantidade de uniformes escolares, oferecendo descontos exclusivos para escolas e instituições de ensino.",
    "2023-08-14": "Destaque roupas inovadoras e funcionais para estudantes, incluindo peças com tecnologia de tecido avançada e designs modernos.",
    "2023-08-15": "Ofereça brindes educacionais, como acessórios escolares ou kits de estudo, para compras acima de um determinado valor, incentivando os alunos a adquirirem mais.",
    "2023-08-16": "Promova descontos em roupas temáticas para crianças, como roupas com personagens populares de desenhos animados e filmes, atraindo os alunos mais jovens e seus pais.",
    "2023-08-17": "Lance uma campanha interativa de volta às aulas nas redes sociais, incentivando os alunos e seus pais a compartilharem fotos do primeiro dia de aula com as roupas da loja.",
    "2023-08-18": "Destaque roupas escolares ecológicas e sustentáveis, promovendo a consciência ambiental entre os alunos e suas famílias.",
    "2023-08-19": "Realize uma promoção de fim de semana com descontos especiais em artigos de vestuário escolar, incentivando os alunos a renovarem seus guarda-roupas para o novo ano letivo.",
    "2023-08-20": "Organize uma 'Semana da Arte Escolar' com descontos em roupas e acessórios para atividades artísticas, estimulando a criatividade entre os alunos.",
    "2023-08-21": "Promova um desafio de desenho ou escrita temático nas redes sociais, oferecendo prêmios exclusivos de roupas ou acessórios escolares para os vencedores.",
    "2023-08-22": "Lance kits DIY (Faça Você Mesmo) de roupas escolares, fornecendo materiais e instruções para os alunos customizarem suas próprias peças de roupa.",
    "2023-08-23": "Destaque a importância de ter um guarda-roupa escolar versátil e funcional, incentivando os alunos a escolherem peças que possam ser usadas em diferentes ocasiões.",
    "2023-08-24": "Promova uma venda-relâmpago com descontos em itens de vestuário de alta rotatividade, oferecendo aos alunos a oportunidade de adquirirem peças populares por preços acessíveis.",
    "2023-08-25": "Realize um workshop de caligrafia e lettering para estudantes, incentivando a criatividade e o aprimoramento das habilidades de escrita dos alunos.",
    "2023-08-26": "Destaque roupas escolares que são perfeitas para presentear, como itens personalizados e acessórios únicos para os alunos.",
    "2023-08-27": "Lance uma promoção especial de 'Final de Mês' em roupas escolares, oferecendo descontos adicionais para impulsionar as vendas antes do final do mês.",
    "2023-08-28": "Ofereça workshops interativos sobre como utilizar certos produtos de vestuário escolar, proporcionando aos alunos dicas e truques para maximizar o uso de suas roupas.",
    "2023-08-29": "Destaque a importância de manter um armário escolar bem organizado e promova produtos que possam ajudar os alunos a manterem suas roupas e acessórios em ordem.",
    "2023-08-30": "Inicie uma parceria com escolas locais, oferecendo descontos especiais em uniformes e acessórios para os alunos, fortalecendo os laços com a comunidade escolar.",
    "2023-08-31": "Agradeça aos alunos e seus pais pelo apoio contínuo durante o mês de agosto, oferecendo uma oferta especial ou desconto exclusivo"

};

export const dailyTasksSetembro: IDailyProps = {
    "2023-09-01": "Lance uma nova coleção de roupas de outono com cores e estilos da temporada.",
    "2023-09-02": "Promova um desconto especial em camisas e blusas para preparar os clientes para a meia-estação.",
    "2023-09-03": "Organize um desfile de moda virtual nas redes sociais para exibir as últimas tendências.",
    "2023-09-04": "Ofereça um brinde exclusivo para compras de peças de roupa acima de um determinado valor.",
    "2023-09-05": "Crie um guia de estilo de moda de outono para os clientes se inspirarem em novas combinações.",
    "2023-09-06": "Promova uma venda de fim de semana focada em acessórios de outono, como lenços e chapéus.",
    "2023-09-07": "Destaque a importância da moda sustentável e ofereça descontos em roupas de materiais reciclados.",
    "2023-09-08": "Lance kits de guarda-roupa essenciais para a transição do verão para o outono.",
    "2023-09-09": "Realize uma sessão de perguntas e respostas ao vivo com um estilista local para fornecer dicas de moda de outono.",
    "2023-09-10": "Promova um concurso de estilo de moda de outono, incentivando os clientes a compartilharem seus looks.",
    "2023-09-11": "Ofereça descontos em casacos e jaquetas para se preparar para os dias mais frios.",
    "2023-09-12": "Crie pacotes de roupas de outono completos com descontos especiais para os clientes.",
    "2023-09-13": "Destaque marcas de roupas sustentáveis e éticas em suas redes sociais e site.",
    "2023-09-14": "Lance uma linha de roupas de academia e promova um estilo de vida saudável.",
    "2023-09-15": "Promova uma venda especial em calçados de outono, como botas e sapatos fechados.",
    "2023-09-16": "Realize um workshop sobre dicas de moda de outono e como criar looks versáteis com poucas peças.",
    "2023-09-17": "Lance uma promoção 'Compre um e Leve o Segundo pela Metade do Preço' em itens selecionados de outono.",
    "2023-09-18": "Destaque marcas locais e artesanais de roupas para apoiar a comunidade.",
    "2023-09-19": "Promova uma venda-relâmpago de roupas infantis para a temporada de outono.",
    "2023-09-20": "Inicie uma campanha de indicação, onde os clientes podem ganhar descontos ao referir amigos para a loja.",
    "2023-09-21": "Celebre o Dia da Árvore com uma linha de roupas eco-friendly e promova a consciência ambiental.",
    "2023-09-22": "Organize um evento de lançamento de uma nova linha de roupas de noite ou festa.",
    "2023-09-23": "Destaque a importância de roupas confortáveis e práticas para o dia a dia.",
    "2023-09-24": "Promova um desconto em roupas de malha e suéteres para os dias mais frios de outono.",
    "2023-09-25": "Lance um desafio de estilo de moda casual, incentivando os clientes a compartilharem seus visuais casuais favoritos.",
    "2023-09-26": "Destaque roupas de alta qualidade e duráveis para construir um guarda-roupa duradouro.",
    "2023-09-27": "Ofereça frete grátis para compras acima de um determinado valor de roupas de outono.",
    "2023-09-28": "Promova um workshop sobre como montar looks elegantes e confortáveis para o trabalho com roupas de outono.",
    "2023-09-29": "Realize uma venda especial focada em roupas de viagem e aventura para o outono.",
    "2023-09-30": "Agradeça aos clientes por um mês incrível com um cupom de desconto válido para sua próxima compra de roupas.",
};
export const dailyTasksOutubro: IDailyProps = {
    "2023-10-01": "Inicie outubro promovendo produtos de moda outono/inverno, como casacos e suéteres.",
    "2023-10-02": "Realize um concurso de estilo de outono, incentivando os clientes a compartilharem seus melhores looks para a estação.",
    "2023-10-03": "Ofereça workshops sobre dicas de moda de outono e como criar combinações únicas.",
    "2023-10-04": "Lance uma linha especial de acessórios de outono, como cachecóis e luvas.",
    "2023-10-05": "Promova uma venda de meio de semana com descontos em itens selecionados de moda outono/inverno.",
    "2023-10-06": "Organize um evento de lançamento para uma nova coleção de roupas de outono.",
    "2023-10-07": "Destaque roupas e acessórios que são ideais para presentes, como conjuntos de cachecol e luva ou conjuntos de camiseta e suéter.",
    "2023-10-08": "Promova uma venda-relâmpago focada em itens essenciais de outono, como botas e jaquetas.",
    "2023-10-09": "Lance um desafio de moda nas redes sociais, incentivando os clientes a compartilharem suas combinações de roupas de outono favoritas.",
    "2023-10-10": "Promova produtos voltados para a organização de guarda-roupa e espaço de armazenamento.",
    "2023-10-11": "Ofereça descontos em conjuntos de roupas para a transição do outono para o inverno.",
    "2023-10-12": "Celebre o Dia das Crianças com promoções e descontos em roupas infantis.",
    "2023-10-13": "Promova um workshop de moda para pais e filhos, incentivando a criação de looks coordenados.",
    "2023-10-14": "Lance uma campanha de volta às aulas de moda com descontos em roupas e acessórios essenciais para os estudantes.",
    "2023-10-15": "Ofereça frete grátis para compras acima de um valor determinado de roupas e acessórios de outono/inverno.",
    "2023-10-16": "Promova uma venda de produtos temáticos de outono, destacando cores e designs sazonais de roupas.",
    "2023-10-17": "Lance um concurso de histórias ou poesias sobre o outono, incentivando os clientes a compartilharem suas criações nas redes sociais.",
    "2023-10-18": "Organize um webinar sobre como escolher roupas de acordo com o estilo pessoal e o clima.",
    "2023-10-19": "Destaque roupas ecológicas e sustentáveis, promovendo a consciência ambiental e marcas que seguem práticas éticas.",
    "2023-10-20": "Realize uma venda de fim de semana focada em roupas casuais e confortáveis para o outono.",
    "2023-10-21": "Lance kits DIY (Faça Você Mesmo) para personalização de roupas de outono.",
    "2023-10-22": "Promova um desconto em roupas e acessórios para eventos e ocasiões especiais.",
    "2023-10-23": "Destaque marcas de roupas locais e artesanais para apoiar a comunidade e incentivar o comércio local.",
    "2023-10-24": "Ofereça um brinde especial para compras de roupas acima de um valor determinado.",
    "2023-10-25": "Realize um concurso de fotos de outono, incentivando os clientes a compartilharem fotos vestindo suas roupas favoritas da loja.",
    "2023-10-26": "Lance uma promoção 'Compre um e Leve o Segundo pela Metade do Preço' em itens selecionados de outono/inverno.",
    "2023-10-27": "Organize um evento de moda local, apresentando designers e marcas da região.",
    "2023-10-28": "Promova uma venda-relâmpago em roupas e acessórios de inverno antecipados.",
    "2023-10-29": "Ofereça descontos em roupas de malha e acessórios quentes para os dias mais frios de outono.",
    "2023-10-30": "Lance uma última venda de outono, com descontos em produtos de inverno antecipados.",
    "2023-10-31": "Celebre o Dia das Bruxas oferecendo promoções especiais e descontos em toda a loja. E agradeça aos clientes por um mês incrível com um cupom de desconto válido para sua próxima compra de roupas.",
};


export const dailyTasksNovembro: IDailyProps = {
    "2023-11-01": "Comece novembro promovendo roupas e acessórios para festas de fim de ano e celebrações de final de ano.",
    "2023-11-02": "Celebre o Dia de Finados com uma promoção especial em roupas e acessórios para um look reflexivo e respeitoso.",
    "2023-11-03": "Lance uma nova coleção de roupas temáticas de Natal e prepare sua loja para a temporada festiva.",
    "2023-11-04": "Realize um workshop de estilo festivo para ajudar os clientes a escolherem os melhores trajes para as festas de fim de ano.",
    "2023-11-05": "Promova uma venda de roupas e acessórios para artistas, como pincéis, tintas e telas.",
    "2023-11-06": "Lance uma promoção focada em roupas e acessórios elegantes para presentes de fim de ano.",
    "2023-11-07": "Organize um evento de DIY (Faça Você Mesmo) para clientes criarem seus próprios acessórios festivos.",
    "2023-11-08": "Destaque roupas e acessórios sustentáveis ou ecológicos, promovendo uma abordagem consciente para o feriado.",
    "2023-11-09": "Inicie uma série de posts nas redes sociais destacando ideias de presentes de moda para diferentes grupos.",
    "2023-11-10": "Lance um desafio de estilo e organização, incentivando os clientes a se prepararem para o final de ano com um guarda-roupa adequado.",
    "2023-11-11": "Ofereça uma promoção especial para o Dia dos Solteiros, destacando roupas confortáveis e elegantes para o autocuidado.",
    "2023-11-12": "Promova uma venda-relâmpago com descontos em peças de moda populares.",
    "2023-11-13": "Realize um evento online dando dicas sobre como criar looks únicos e festivos com roupas e acessórios da sua loja.",
    "2023-11-14": "Lance kits de presente personalizados, permitindo que os clientes escolham peças específicas para criar o presente perfeito.",
    "2023-11-15": "Comemore a Proclamação da República com promoções especiais e destaque produtos relacionados ao Brasil.",
    "2023-11-16": "Ofereça oficinas sobre como montar looks festivos, ensinando aos clientes as melhores combinações e estilos para diferentes eventos.",
    "2023-11-17": "Promova uma venda de fim de semana com descontos em roupas essenciais para a temporada de festas.",
    "2023-11-18": "Destaque produtos que ajudam no planejamento financeiro e incentive presentes econômicos e inteligentes para o final de ano.",
    "2023-11-19": "Incentive os clientes a começarem a comprar presentes de Natal agora, evitando a correria de última hora.",
    "2023-11-20": "Lance uma promoção 'Compre um e Leve o Segundo pela Metade do Preço' em roupas selecionadas.",
    "2023-11-21": "Promova uma noite de compras especial com horário estendido e descontos exclusivos em roupas e acessórios.",
    "2023-11-22": "Lance uma linha especial de cartões de agradecimento, incentivando a gratidão durante esta temporada festiva.",
    "2023-11-23": "Realize um sorteio com a chance de ganhar roupas e acessórios populares ou um voucher de compras para a loja.",
    "2023-11-24": "Ofereça frete grátis para todas as compras como uma promoção pré-Black Friday.",
    "2023-11-25": "Continue as promoções da Black Friday, talvez com ofertas especiais que mudam a cada hora para criar um senso de urgência entre os clientes.",
    "2023-11-26": "Promova o 'Small Business Saturday', incentivando os clientes a apoiar pequenas empresas locais, incluindo a sua loja de roupas.",
    "2023-11-27": "Ofereça promoções especiais para a Cyber Monday, com foco em roupas exclusivas online e acessórios de moda.",
    "2023-11-28": "Realize um webinar sobre as tendências de moda para o próximo ano, mantendo os clientes informados sobre o que está por vir.",
    "2023-11-29": "Lance um desafio de 30 dias de gratidão nas redes sociais, incentivando os seguidores a compartilharem diariamente algo pelo qual são gratos, incluindo suas peças de moda favoritas.",
    "2023-11-30": "Encerre novembro agradecendo aos seus clientes por um mês maravilhoso e ofereça um teaser do que esperar em dezembro com novas coleções e promoções emocionantes.",
};

  export const dailyTasksDezembro: IDailyProps = {
    "2023-12-01": "Inicie dezembro com uma grande venda de roupas de inverno, destacando novos produtos e best-sellers para a temporada.",
    "2023-12-02": "Promova um workshop de moda de inverno, fornecendo dicas de estilo e como se vestir adequadamente para o clima frio.",
    "2023-12-03": "Lance uma promoção '12 dias de descontos em roupas', com uma oferta especial em peças selecionadas a cada dia.",
    "2023-12-04": "Promova uma venda relâmpago de itens de inverno, como casacos, cachecóis e botas.",
    "2023-12-05": "Ofereça embrulho de presente gratuito com qualquer compra de roupas ou acessórios.",
    "2023-12-06": "Destaque roupas perfeitas para festas de fim de ano, como vestidos de festa e trajes formais.",
    "2023-12-07": "Lance um concurso de moda nas redes sociais, onde os clientes podem ganhar um prêmio mostrando seus melhores looks festivos.",
    "2023-12-08": "Celebre o Dia da Família promovendo roupas que podem ser desfrutadas por todos, como pijamas e conjuntos combinados para a família.",
    "2023-12-09": "Realize um evento especial para clientes VIP com descontos exclusivos e acesso antecipado a novas coleções de inverno.",
    "2023-12-10": "Ofereça uma promoção onde os clientes recebem um acessório de inverno gratuito nas compras acima de um determinado valor.",
    "2023-12-11": "Realize um workshop sobre como criar looks festivos e elegantes para as festas de fim de ano.",
    "2023-12-12": "Promova uma venda 'Compre um, Dê um' para incentivar a doação de roupas de inverno para instituições de caridade.",
    "2023-12-13": "Dê destaque às tendências de inverno mais populares da temporada com descontos especiais.",
    "2023-12-14": "Ofereça frete expresso gratuito para garantir a entrega das compras de roupas antes das festas de fim de ano.",
    "2023-12-15": "Realize um evento de apreciação ao cliente com desfiles de moda, música e descontos exclusivos na loja.",
    "2023-12-16": "Promova os últimos produtos restantes da sua promoção '12 dias de descontos em roupas'.",
    "2023-12-17": "Ofereça descontos em roupas de inverno para presentes de última hora.",
    "2023-12-18": "Garanta que todos os pedidos online de roupas sejam enviados a tempo para as festas de fim de ano.",
    "2023-12-19": "Promova uma venda de acessórios de inverno, como luvas, chapéus e cachecóis temáticos.",
    "2023-12-20": "Lance um desafio nas redes sociais para os clientes compartilharem seus looks festivos favoritos usando produtos da sua loja.",
    "2023-12-21": "Realize uma venda relâmpago focada em suéteres e blusas quentes para o inverno.",
    "2023-12-22": "Dê aos clientes uma prévia das tendências de moda e promoções que você está planejando para o próximo ano.",
    "2023-12-23": "Ofereça uma promoção especial de Natal para compras de roupas de última hora na véspera da véspera de Natal.",
    "2023-12-24": "Agradeça aos seus clientes por um ano maravilhoso e deseje-lhes um Feliz Natal com descontos finais de véspera de Natal.",
    "2023-12-25": "Celebre o Dia de Natal com uma mensagem especial de agradecimento e um código de desconto válido para o próximo ano.",
    "2023-12-26": "Lance as promoções pós-Natal em roupas e acessórios de inverno, dando aos clientes ofertas especiais para a temporada.",
    "2023-12-27": "Promova uma venda de fim de ano em roupas e acessórios, preparando os clientes para o Ano Novo.",
    "2023-12-28": "Destaque produtos de planejamento e resoluções, como roupas esportivas e de treino, para incentivar um estilo de vida saudável no próximo ano.",
    "2023-12-29": "Ofereça um workshop online sobre como se preparar e manter a motivação para um ano de estilo e moda.",
    "2023-12-30": "Lance uma venda 'Adeus, 2023!' com descontos em roupas selecionadas para o fim do ano.",
    "2023-12-31": "Agradeça aos seus clientes por um ano incrível e deseje-lhes um próspero Ano Novo com uma mensagem especial de gratidão e votos para o próximo ano.",
};
