export interface IDailyProps {
  [key: string]: string;
}
export const dailyTasksJaneiro: IDailyProps = {
  "2023-01-01": "Inicie um desconto especial para agendas e calendários, incentivando os clientes a planejar 2023.",
  "2023-01-02": "Promoção de kits de organização com etiquetas, post-its e canetas coloridas.",
  "2023-01-03": "Workshop online sobre planejamento eficaz usando ferramentas de papelaria.",
  "2023-01-04": "Desconto em itens de escritório para aqueles que estão trabalhando em casa.",
  "2023-01-05": "Lançamento de novos produtos temáticos para o início do ano.",
  "2023-01-06": "Ofereça uma aula de caligrafia básica na loja ou virtualmente.",
  "2023-01-07": "Promoção de produtos ecológicos e sustentáveis.",
  "2023-01-08": "Dia de ofertas especiais para estudantes com apresentação de carteirinha.",
  "2023-01-09": "Dê destaque a cadernos e diários, incentivando a escrita como forma de autoconhecimento.",
  "2023-01-10": "Promoção 'Leve 3, Pague 2' em marcadores coloridos.",
  "2023-01-11": "Workshop sobre a arte do scrapbooking.",
  "2023-01-12": "Desconto especial em itens de bullet journal.",
  "2023-01-13": "Realize um concurso de design de capa de caderno nas redes sociais.",
  "2023-01-14": "Destaque para itens de papelaria personalizados.",
  "2023-01-15": "Desconto em cartuchos e refis de caneta.",
  "2023-01-16": "Promoção para compras em atacado para pequenos empreendedores.",
  "2023-01-17": "Dê destaque a kits de papelaria para presentear.",
  "2023-01-18": "Workshop sobre organização de planner.",
  "2023-01-19": "Desconto especial em envelopes e papel de carta.",
  "2023-01-20": "Promoção relâmpago em itens selecionados até o final do dia.",
  "2023-01-21": "Dê destaque a itens de papelaria vintage ou retrô.",
  "2023-01-22": "Promoção 'Compre um, Leve outro' em adesivos decorativos.",
  "2023-01-23": "Desconto em itens para organização de escritório.",
  "2023-01-24": "Destaque para canetas artísticas e material para desenho.",
  "2023-01-25": "Liquidação de itens de coleções anteriores.",
  "2023-01-26": "Desconto especial para compras online.",
  "2023-01-27": "Ofereça embalagens de presente gratuitas para qualquer compra na loja.",
  "2023-01-28": "Promova os produtos mais vendidos do mês.",
  "2023-01-29": "Desconto em produtos para estudantes em preparação para volta às aulas.",
  "2023-01-30": "Workshop de artes com produtos de papelaria.",
  "2023-01-31": "Anúncio de novos produtos que chegarão em fevereiro.",
};

export const dailyTasksFevereiro: IDailyProps = {
  "2023-02-01": "Lançamento de produtos temáticos para o Dia dos Namorados.",
  "2023-02-02": "Promoção de itens vermelhos e rosas em celebração ao mês do amor.",
  "2023-02-03": "Workshop sobre criação de cartões artesanais para o Dia dos Namorados.",
  "2023-02-04": "Desconto em produtos para presentes, incentivando compras antecipadas para o Dia dos Namorados.",
  "2023-02-05": "Destaque para produtos de papelaria com frases românticas.",
  "2023-02-06": "Ofereça um brinde em compras acima de um determinado valor.",
  "2023-02-07": "Workshop de escrita criativa focado em cartas de amor.",
  "2023-02-08": "Desconto em produtos de papelaria de luxo.",
  "2023-02-09": "Ofereça personalização gratuita em itens selecionados.",
  "2023-02-10": "Promoção 'Compre um presente e ganhe desconto no segundo item'.",
  "2023-02-11": "Ofereça sugestões de presentes criativos para o Dia dos Namorados.",
  "2023-02-12": "Desconto em kits de papelaria para casais.",
  "2023-02-13": "Ofereça entrega gratuita para compras de última hora do Dia dos Namorados.",
  "2023-02-14": "Celebre o Dia dos Namorados com brindes e promoções especiais.",
  "2023-02-15": "Incentive os feedbacks de clientes sobre produtos comprados para o Dia dos Namorados.",
  "2023-02-16": "Promoção em itens relacionados à volta às aulas.",
  "2023-02-17": "Destaque para cadernos e materiais escolares ecológicos.",
  "2023-02-18": "Workshop sobre técnicas de estudo usando ferramentas de papelaria.",
  "2023-02-19": "Promova produtos que ajudam na organização de tarefas e estudos.",
  "2023-02-20": "Desconto em mochilas e estojos escolares.",
  "2023-02-21": "Ofereça kits de estudo personalizados para diferentes faixas etárias.",
  "2023-02-22": "Promova itens de arte e desenho para estudantes de design e artes.",
  "2023-02-23": "Desconto em produtos de papelaria para professores.",
  "2023-02-24": "Promoção 'Leve 3, Pague 2' em canetas de diferentes marcas.",
  "2023-02-25": "Incentive a compra de produtos sustentáveis oferecendo um brinde ecológico.",
  "2023-02-26": "Promova um concurso de desenho infantil com premiações em produtos de papelaria.",
  "2023-02-27": "Destaque para produtos inovadores que acabaram de chegar em sua loja.",
  "2023-02-28": "Liquidação de fim de mês e prévia das novidades que chegarão em março."
};
export const dailyTasksMarco: IDailyProps = {
  "2023-03-01": "Comece o mês com novas chegadas! Destaque as novas linhas de produtos de papelaria para a primavera e incentive os clientes a renovar seus suprimentos.",
  "2023-03-02": "Promova uma sessão de perguntas e respostas sobre técnicas de scrapbooking nas redes sociais.",
  "2023-03-03": "Destaque os produtos mais vendidos da semana anterior com descontos especiais.",
  "2023-03-04": "Organize um workshop de caligrafia usando canetas da sua loja.",
  "2023-03-05": "Ofereça brindes em compras acima de um determinado valor para incentivar mais vendas.",
  "2023-03-06": "Realize uma venda flash de 24 horas em produtos selecionados.",
  "2023-03-07": "Lance um programa de fidelidade para incentivar os clientes a retornar e comprar mais.",
  "2023-03-08": "Comemore o Dia Internacional da Mulher com ofertas especiais para produtos femininos e destaque as empreendedoras na indústria da papelaria.",
  "2023-03-09": "Divulgue um concurso de desenho infantil com prêmios emocionantes para as crianças.",
  "2023-03-10": "Lance um novo workshop virtual sobre técnicas de scrapbooking e desenho usando seus produtos de papelaria.",
  "2023-03-11": "Ofereça descontos em cadernos e blocos de notas para incentivar o planejamento e a organização pessoal.",
  "2023-03-12": "Promova uma venda de fim de semana com descontos especiais em toda a loja.",
  "2023-03-13": "Incentive os clientes a deixar avaliações e comentários positivos sobre seus produtos nas redes sociais e site.",
  "2023-03-14": "Destaque os produtos mais vendidos da semana anterior com descontos especiais.",
  "2023-03-15": "Promoção de meados de março! Ofereça descontos em produtos selecionados e promova em suas redes sociais.",
  "2023-03-16": "Realize uma sessão de autógrafos virtual com um autor de livros relacionados à papelaria.",
  "2023-03-17": "Lance uma linha de produtos de papelaria com tema de Páscoa, incluindo cartões, papel de embrulho e decorações.",
  "2023-03-18": "Realize uma promoção de Páscoa com descontos em produtos temáticos e cestas de presentes.",
  "2023-03-19": "Organize uma oficina de arte para crianças usando seus produtos de papelaria como ferramentas criativas.",
  "2023-03-20": "Dia Mundial da Felicidade! Ofereça um brinde pequeno em todas as compras para espalhar alegria.",
  "2023-03-21": "Celebre o início da primavera com novos designs de papel de carta e cadernos temáticos.",
  "2023-03-22": "Destaque seus produtos de escrita, como canetas e lápis, com descontos especiais.",
  "2023-03-23": "Realize uma enquete nas redes sociais para pedir sugestões de produtos dos clientes.",
  "2023-03-24": "Promova uma venda-relâmpago de 12 horas em itens de papelaria favoritos dos clientes.",
  "2023-03-25": "Realize um sorteio nas redes sociais com um grande prêmio, como um conjunto completo de material de arte.",
  "2023-03-26": "Ofereça frete grátis para compras acima de um determinado valor durante o fim de semana.",
  "2023-03-27": "Incentive os clientes a compartilhar fotos de seus produtos de papelaria em uso com uma hashtag exclusiva.",
  "2023-03-28": "Destaque produtos de escrita premium e ofereça uma promoção de 'Compra 1, Leve 1' para canetas selecionadas.",
  "2023-03-29": "Lance uma linha de produtos temáticos de jardinagem para a primavera, incluindo papel decorativo com estampas de flores.",
  "2023-03-30": "Promova uma venda de estoque limpo para se livrar de produtos com baixo estoque antes do final do mês.",
  "2023-03-31": "Termine o mês revendo seu inventário e planejando promoções e eventos para o próximo mês.",
};

export const dailyTasksAbril: IDailyProps = {
  "2023-04-01": "Celebre o Dia da Mentira com produtos divertidos e inusitados! Ofereça descontos em itens de papelaria com designs e mensagens engraçadas.",
  "2023-04-02": "Promova uma sessão de brainstorming online para coletar ideias de produtos de clientes.",
  "2023-04-03": "Lance uma nova coleção de adesivos temáticos para a primavera.",
  "2023-04-04": "Realize uma venda-relâmpago para produtos específicos e limite-a às primeiras 50 compras.",
  "2023-04-05": "Colabore com um influenciador digital local para promover seus produtos em suas redes sociais.",
  "2023-04-06": "Dê descontos em produtos eco-friendly em antecipação ao Dia da Terra.",
  "2023-04-07": "Lance uma campanha de marketing digital focada em produtos sustentáveis.",
  "2023-04-08": "Ofereça uma promoção especial para o Dia Internacional do Desenho com descontos em materiais de arte.",
  "2023-04-09": "Realize uma competição de arte online para artistas locais com prêmios emocionantes.",
  "2023-04-10": "Promova produtos de papelaria relacionados a viagens e aventuras para as férias da primavera.",
  "2023-04-11": "Ofereça descontos em cadernos e blocos de notas personalizados para planejamento de viagens.",
  "2023-04-12": "Incentive os clientes a compartilhar histórias de suas aventuras com produtos da sua loja nas redes sociais.",
  "2023-04-13": "Destaque kits de papelaria para viagens, incluindo cadernos de bolso, canetas e envelopes.",
  "2023-04-14": "Realize uma venda-relâmpago em produtos selecionados, limitado às primeiras 100 compras.",
  "2023-04-15": "Promova produtos de arte para crianças para manter a criatividade fluindo durante as férias.",
  "2023-04-16": "Ofereça um workshop virtual sobre scrapbooking para memórias de viagem.",
  "2023-04-17": "Destaque os mais novos designs de papel de carta e envelopes para comunicação pessoal.",
  "2023-04-18": "Promova uma venda especial de 'Meio do Mês' com descontos em produtos selecionados.",
  "2023-04-19": "Ofereça descontos para clientes que trazem materiais de papelaria usados para reciclagem.",
  "2023-04-20": "Celebre o Dia da Terra com promoções em produtos ecológicos e sustentáveis.",
  "2023-04-21": "Incentive os clientes a plantar uma árvore ao comprar produtos específicos.",
  "2023-04-22": "Lance um novo produto de papelaria em colaboração com uma marca ecológica.",
  "2023-04-23": "Ofereça descontos em produtos de papelaria temáticos de jardinagem e natureza.",
  "2023-04-24": "Promova um concurso nas redes sociais com um tema ecológico, premiando as melhores ideias sustentáveis.",
  "2023-04-25": "Lance uma linha de cadernos feitos com papel reciclado e tintas à base de água.",
  "2023-04-26": "Destaque produtos de papelaria inspirados na natureza, como estampas florais e animais.",
  "2023-04-27": "Ofereça um workshop sobre a criação de artesanato de papel sustentável.",
  "2023-04-28": "Promova uma venda-relâmpago de fim de semana para limpar estoques antes de maio.",
  "2023-04-29": "Incentive os clientes a escrever cartas manuscritas para amigos e familiares.",
  "2023-04-30": "Finalize o mês com uma revisão das vendas e planeje eventos e promoções para maio.",
};
export const dailyTasksMaio: IDailyProps = {
  "2023-05-01": "Celebre o Dia do Trabalho com descontos especiais para funcionários de escolas e escritórios. Destaque produtos de papelaria que facilitam a produtividade.",
  "2023-05-02": "Lance novos designs de papelaria com temas de primavera e verão.",
  "2023-05-03": "Realize uma sessão de Q&A (Perguntas e Respostas) online sobre técnicas de organização usando planners e agendas.",
  "2023-05-04": "Promova uma 'Semana da Gratidão', incentivando os clientes a escrever cartões de agradecimento para entes queridos.",
  "2023-05-05": "Celebre o Cinco de Mayo com descontos especiais em produtos coloridos e festivos.",
  "2023-05-06": "Ofereça workshops de DIY (faça você mesmo) para crianças usando itens de papelaria.",
  "2023-05-07": "Promova uma venda de domingo com descontos especiais em produtos selecionados.",
  "2023-05-08": "Destaque produtos relacionados à arte e criatividade, como tintas, pincéis e papéis especiais.",
  "2023-05-09": "Promova uma campanha de mídia social focada em técnicas de journaling.",
  "2023-05-10": "Ofereça um brinde especial nas compras acima de um valor determinado para celebrar o Dia das Mães que se aproxima.",
  "2023-05-11": "Promova um concurso nas redes sociais onde os clientes podem ganhar um kit de papelaria para o Dia das Mães.",
  "2023-05-12": "Lance produtos personalizados perfeitos para presentes do Dia das Mães.",
  "2023-05-13": "Ofereça embalagens de presente gratuitas para qualquer compra relacionada ao Dia das Mães.",
  "2023-05-14": "Celebre o Dia das Mães destacando histórias de mães empreendedoras na indústria da papelaria.",
  "2023-05-15": "Inicie uma promoção de meados de mês com descontos especiais em produtos selecionados.",
  "2023-05-16": "Promova produtos sustentáveis em antecipação ao Dia Mundial do Meio Ambiente.",
  "2023-05-17": "Lance um programa de reciclagem na loja, incentivando os clientes a trazer itens de papelaria usados.",
  "2023-05-18": "Destaque os benefícios dos produtos eco-friendly, como cadernos feitos de papel reciclado.",
  "2023-05-19": "Organize um evento local de troca de livros e materiais de escritório.",
  "2023-05-20": "Promova um desconto especial para estudantes que se preparam para exames finais e necessitam de materiais de revisão.",
  "2023-05-21": "Colabore com artistas locais para criar designs exclusivos para sua linha de produtos.",
  "2023-05-22": "Promova uma venda-relâmpago de 48 horas em itens de arte e artesanato.",
  "2023-05-23": "Incentive os clientes a compartilhar suas criações artísticas usando seus produtos em plataformas de mídia social.",
  "2023-05-24": "Ofereça tutoriais em vídeo sobre técnicas de arte e artesanato usando produtos da sua loja.",
  "2023-05-25": "Promova uma venda especial de 'Final de Mês' com grandes descontos em produtos populares.",
  "2023-05-26": "Realize um evento de apreciação do cliente com ofertas especiais e refreshments na loja.",
  "2023-05-27": "Ofereça frete grátis para compras online durante o fim de semana.",
  "2023-05-28": "Celebre o Dia Mundial do Brincar destacando produtos de papelaria divertidos e lúdicos para crianças.",
  "2023-05-29": "Lance um novo produto ou linha de produtos exclusivos para o verão.",
  "2023-05-30": "Ofereça uma promoção 'Compre 1, Leve 1 Grátis' em produtos selecionados.",
  "2023-05-31": "Encerre o mês agradecendo aos clientes leais com uma nota especial nas redes sociais e por e-mail.",
};

export const dailyTasksJunho: IDailyProps = {
  "2023-06-01": "Inicie o mês celebrando o verão com produtos de papelaria com temas de praia e férias.",
  "2023-06-02": "Destaque itens essenciais para viagens, como cadernos de viagem e kits de desenho portáteis.",
  "2023-06-03": "Ofereça workshops de criação de cartões postais e diários de viagem.",
  "2023-06-04": "Lance uma promoção de 'Compre Mais, Economize Mais' para incentivar compras maiores.",
  "2023-06-05": "No Dia Mundial do Meio Ambiente, ofereça descontos em produtos sustentáveis e promova práticas ecológicas.",
  "2023-06-06": "Colabore com um influenciador local para um sorteio de produtos de papelaria nas redes sociais.",
  "2023-06-07": "Destaque itens de papelaria perfeitos para festas de verão e piqueniques.",
  "2023-06-08": "Lance um desafio de 30 dias de journaling com prompts diários para inspirar a criatividade.",
  "2023-06-09": "Realize uma venda-relâmpago de fim de semana em produtos selecionados.",
  "2023-06-10": "Ofereça um workshop sobre técnicas de bullet journaling e planejamento eficiente.",
  "2023-06-11": "Promova itens de papelaria voltados para casamentos, como livros de visitas e cartões.",
  "2023-06-12": "Celebre o Dia dos Namorados brasileiro com produtos românticos e ofertas especiais.",
  "2023-06-13": "Ofereça frete grátis para todas as compras online por um período limitado.",
  "2023-06-14": "Promova uma venda de 'Meio do Mês' com descontos especiais em produtos selecionados.",
  "2023-06-15": "Lance um clube de assinatura mensal onde os membros recebem novos produtos de papelaria todo mês.",
  "2023-06-16": "Destaque produtos perfeitos para festas de formatura e presentes de agradecimento aos professores.",
  "2023-06-17": "Ofereça um brinde especial em compras acima de um valor determinado durante o fim de semana.",
  "2023-06-18": "Organize um evento na loja com demonstrações de produtos e workshops.",
  "2023-06-19": "Ofereça uma promoção 'Compre 2, Leve 3' em categorias de produtos selecionados.",
  "2023-06-20": "Promova produtos de papelaria que são perfeitos para presentear no Dia dos Pais.",
  "2023-06-21": "Celebre o solstício de verão com um evento temático e promoções especiais.",
  "2023-06-22": "Lance uma linha de produtos de papelaria com temas tropicais e de praia.",
  "2023-06-23": "Ofereça descontos especiais para estudantes e professores para se prepararem para o próximo ano letivo.",
  "2023-06-24": "Promova um desafio nas redes sociais onde os clientes podem mostrar seu espaço de trabalho ou estudo em casa.",
  "2023-06-25": "Ofereça um workshop sobre técnicas de caligrafia e escrita à mão.",
  "2023-06-26": "Inicie uma venda de fim de mês com descontos significativos em itens selecionados.",
  "2023-06-27": "Promova uma 'Semana de Apreciação do Cliente' com ofertas diárias exclusivas.",
  "2023-06-28": "Ofereça embalagem de presente gratuita com qualquer compra para incentivar presentes de aniversário e outras ocasiões.",
  "2023-06-29": "Destaque produtos de papelaria inspirados em destinos de viagem populares.",
  "2023-06-30": "Agradeça aos seus clientes pelo apoio contínuo e dê uma prévia das promoções e eventos planejados para julho.",
};
export const dailyTasksJulho: IDailyProps = {
  "2023-07-01": "Lance uma coleção de verão para produtos de papelaria, com temas de férias, praia e sol.",
  "2023-07-02": "Promova um desconto em itens de papelaria relacionados a viagens, como diários de viagem e mapas raspadinhas.",
  "2023-07-03": "Organize um workshop sobre scrapbooking para ajudar os clientes a preservar suas memórias de férias.",
  "2023-07-04": "Celebre o meio do ano com uma promoção de 'Metade do Ano, Meio Preço' em produtos selecionados.",
  "2023-07-05": "Realize um concurso de arte em papelaria onde os clientes podem enviar designs de verão para um novo produto.",
  "2023-07-06": "Ofereça um desconto especial em itens relacionados a planejamento, como agendas e planners, para ajudar as pessoas a se organizarem para o segundo semestre.",
  "2023-07-07": "Promova uma venda de fim de semana com foco em produtos para estudantes.",
  "2023-07-08": "Lance kits de papelaria temáticos, ideais para presentes de aniversário.",
  "2023-07-09": "Realize uma sessão de Q&A (Perguntas e Respostas) sobre os melhores produtos de papelaria para escritórios domésticos.",
  "2023-07-10": "Ofereça workshops sobre técnicas de desenho e pintura usando produtos da sua loja.",
  "2023-07-11": "Lance uma promoção de 'Volta às Aulas' com descontos em produtos essenciais para estudantes.",
  "2023-07-12": "Inicie uma campanha de doação de material escolar para crianças carentes.",
  "2023-07-13": "Ofereça um desconto em produtos de papelaria voltados para a organização, como pastas, organizadores e etiquetas.",
  "2023-07-14": "Promova um evento na loja com atividades manuais para crianças durante as férias escolares.",
  "2023-07-15": "Lance um desafio nas redes sociais, incentivando os clientes a mostrarem seu espaço de trabalho ou estudo usando produtos da sua loja.",
  "2023-07-16": "Ofereça um brinde exclusivo nas compras acima de um valor determinado.",
  "2023-07-17": "Destaque produtos inovadores que podem melhorar a eficiência no ambiente de trabalho.",
  "2023-07-18": "Lance uma oferta especial para a compra de conjuntos de canetas e marcadores.",
  "2023-07-19": "Organize um webinar sobre técnicas modernas de caligrafia.",
  "2023-07-20": "Lance uma campanha de indicação onde os clientes podem ganhar descontos ao referir amigos.",
  "2023-07-21": "Promova uma venda-relâmpago em produtos de arte, como tintas, pincéis e telas.",
  "2023-07-22": "Destaque os benefícios ambientais dos produtos de papelaria reciclados e promova a consciência ecológica.",
  "2023-07-23": "Realize um sorteio de produtos populares de papelaria nas redes sociais.",
  "2023-07-24": "Destaque os produtos mais vendidos do mês e ofereça pacotes promocionais.",
  "2023-07-25": "Incentive os clientes a deixar avaliações e feedbacks online em troca de um pequeno desconto na próxima compra.",
  "2023-07-26": "Ofereça tutoriais em vídeo sobre como usar certos produtos de papelaria de forma eficaz.",
  "2023-07-27": "Organize uma 'Noite de Artesanato' na loja com demonstrações ao vivo e descontos especiais.",
  "2023-07-28": "Promova um desconto em produtos relacionados a festas, como convites, cartões e embalagens de presente.",
  "2023-07-29": "Realize uma venda especial com foco em produtos para casa e escritório.",
  "2023-07-30": "Ofereça workshops sobre organização pessoal usando planners e bullet journals.",
  "2023-07-31": "Encerre o mês agradecendo aos clientes com uma promoção de última hora ou desconto especial.",
};

export const dailyTasksAgosto: IDailyProps = {
  "2023-08-01": "Comece o mês promovendo produtos voltados para a organização escolar, preparando-se para a volta às aulas.",
  "2023-08-02": "Destaque itens de papelaria que são perfeitos para professores, como planos de aula e diários de classe.",
  "2023-08-03": "Ofereça descontos em pacotes de material escolar para ajudar os pais a se prepararem para o novo ano letivo.",
  "2023-08-04": "Lance novos produtos focados em estudantes universitários.",
  "2023-08-05": "Realize um evento de 'Volta às Aulas' na loja, com demonstrações de produtos e brindes.",
  "2023-08-06": "Promova um desafio nas redes sociais, incentivando os estudantes a compartilharem suas mesas de estudo organizadas.",
  "2023-08-07": "Ofereça frete grátis para compras online de material escolar durante a primeira semana de agosto.",
  "2023-08-08": "Lance um programa de fidelidade para estudantes que oferece descontos e ofertas exclusivas.",
  "2023-08-09": "Realize uma sessão de Q&A (Perguntas e Respostas) sobre os melhores produtos de papelaria para o ano letivo.",
  "2023-08-10": "Promova um desconto em mochilas e estojos para estudantes.",
  "2023-08-11": "Destaque os benefícios de usar agendas e planners para a organização acadêmica.",
  "2023-08-12": "Ofereça um workshop sobre técnicas de estudo eficientes, destacando produtos que podem ajudar.",
  "2023-08-13": "Promova um desconto especial para compras em grande quantidade, ideal para escolas e instituições.",
  "2023-08-14": "Destaque produtos de papelaria inovadores que foram lançados recentemente.",
  "2023-08-15": "Ofereça um brinde educacional nas compras acima de um valor determinado.",
  "2023-08-16": "Promova um desconto em artigos de papelaria temáticos para crianças, como produtos com personagens populares.",
  "2023-08-17": "Lance uma campanha de volta às aulas, incentivando os pais a compartilharem fotos de seus filhos se preparando para o novo ano letivo.",
  "2023-08-18": "Destaque produtos ecológicos e sustentáveis, promovendo a consciência ambiental.",
  "2023-08-19": "Realize uma promoção de fim de semana focada em artigos de escrita, como canetas, lápis e marcadores.",
  "2023-08-20": "Organize uma 'Semana da Arte' promovendo produtos para desenho, pintura e outras atividades artísticas.",
  "2023-08-21": "Promova um desafio de desenho ou escrita nas redes sociais, com prêmios para os vencedores.",
  "2023-08-22": "Lance kits DIY (Faça Você Mesmo) com todos os materiais necessários para projetos de papelaria criativos.",
  "2023-08-23": "Destaque produtos que ajudam na organização pessoal e produtividade.",
  "2023-08-24": "Promova uma venda-relâmpago com descontos em itens de alta rotatividade.",
  "2023-08-25": "Realize um webinar sobre técnicas modernas de caligrafia e lettering.",
  "2023-08-26": "Destaque produtos de papelaria que são ótimos para presentes, como itens personalizados.",
  "2023-08-27": "Lance uma promoção de 'Final de Mês' para impulsionar as vendas.",
  "2023-08-28": "Ofereça workshops sobre como usar certos produtos de papelaria, como carimbos personalizados ou ferramentas de arte.",
  "2023-08-29": "Destaque a importância de ter um espaço de trabalho bem organizado e promova produtos que ajudam nisso.",
  "2023-08-30": "Inicie uma parceria com escolas locais, oferecendo descontos para professores e estudantes.",
  "2023-08-31": "Agradeça aos clientes por um mês incrível com uma oferta especial ou desconto válido apenas para esse dia.",
};
export const dailyTasksSetembro: IDailyProps = {
  "2023-09-01": "Comece setembro com uma venda especial de 'Boas-vindas à Primavera', destacando produtos com temas florais e cores vibrantes.",
  "2023-09-02": "Promova um workshop sobre técnicas de journaling para ajudar os clientes a se expressarem criativamente.",
  "2023-09-03": "Lance uma linha especial de produtos de papelaria focada em bem-estar e mindfulness.",
  "2023-09-04": "Promova um desconto em itens essenciais para estudantes em preparação para os exames finais.",
  "2023-09-05": "Inicie uma campanha de conscientização sobre a importância da reciclagem, destacando produtos ecológicos.",
  "2023-09-06": "Realize um concurso de desenho com temas de primavera, onde os vencedores recebem prêmios em produtos.",
  "2023-09-07": "Celebre o Dia da Independência do Brasil com produtos temáticos e promoções especiais.",
  "2023-09-08": "Lance pacotes de produtos focados em projetos de arte, como pintura ou scrapbooking.",
  "2023-09-09": "Promova uma venda de fim de semana focada em organizadores, agendas e planners.",
  "2023-09-10": "Destaque histórias de clientes que usaram seus produtos para alcançar metas acadêmicas ou profissionais.",
  "2023-09-11": "Ofereça uma promoção especial para professores em reconhecimento à sua dedicação.",
  "2023-09-12": "Promova uma sessão de Q&A (Perguntas e Respostas) sobre os melhores produtos para o ambiente de trabalho.",
  "2023-09-13": "Lance uma campanha de volta às aulas para universitários com descontos em produtos essenciais.",
  "2023-09-14": "Incentive os clientes a compartilharem suas criações de arte usando produtos da sua loja em plataformas de mídia social.",
  "2023-09-15": "Promova uma venda especial em produtos voltados para caligrafia e lettering.",
  "2023-09-16": "Realize um webinar sobre técnicas de estudo e produtos que podem ajudar os estudantes.",
  "2023-09-17": "Lance uma promoção 'Compre um e Leve o Segundo pela Metade do Preço' em itens selecionados.",
  "2023-09-18": "Destaque produtos de papelaria inovadores, especialmente aqueles que incorporam tecnologia.",
  "2023-09-19": "Promova uma venda-relâmpago em produtos de arte, como tintas, pincéis e paletas.",
  "2023-09-20": "Inicie uma campanha de indicação, onde os clientes podem ganhar descontos ao referir amigos.",
  "2023-09-21": "Celebre o Dia da Árvore oferecendo descontos em produtos sustentáveis e ecológicos.",
  "2023-09-22": "Organize um evento de craft night, onde os clientes podem aprender novas habilidades manuais usando produtos da loja.",
  "2023-09-23": "Destaque produtos relacionados a planejamento financeiro e organização de orçamento.",
  "2023-09-24": "Promova um desconto em produtos de papelaria para hobbies, como diários de jardinagem ou cadernos de receitas.",
  "2023-09-25": "Lance um desafio de organização, incentivando os clientes a compartilharem suas dicas e truques usando produtos da sua loja.",
  "2023-09-26": "Destaque produtos feitos à mão ou com designs únicos e exclusivos.",
  "2023-09-27": "Ofereça frete grátis para compras acima de um valor determinado.",
  "2023-09-28": "Promova um workshop sobre técnicas de bullet journaling, mostrando como usar eficientemente os produtos da sua loja.",
  "2023-09-29": "Realize uma venda especial focada em produtos para escrita criativa.",
  "2023-09-30": "Agradeça aos clientes por um mês incrível com um cupom de desconto válido para sua próxima compra.",
};

export const dailyTasksOutubro: IDailyProps = {
  "2023-10-01": "Inicie outubro promovendo produtos de papelaria temáticos de Halloween, como adesivos, cadernos e canetas.",
  "2023-10-02": "Realize um concurso de decoração de cadernos ou diários com temas de Halloween.",
  "2023-10-03": "Ofereça workshops sobre técnicas de desenho com temas de outono e Halloween.",
  "2023-10-04": "Lance uma linha especial de cartões e envelopes para o Dia das Bruxas.",
  "2023-10-05": "Promova uma venda de meio de semana com descontos em produtos selecionados.",
  "2023-10-06": "Organize um evento de craft night com atividades manuais temáticas de Halloween.",
  "2023-10-07": "Destaque produtos que são ótimos para presentes, como kits de papelaria personalizados.",
  "2023-10-08": "Promova uma venda-relâmpago focada em itens de alta rotatividade.",
  "2023-10-09": "Lance um desafio de fotografia, incentivando os clientes a compartilharem fotos de seus espaços de trabalho ou estudo decorados para o Halloween.",
  "2023-10-10": "Promova produtos focados na organização de casa e escritório.",
  "2023-10-11": "Ofereça descontos em produtos voltados para a preparação do NaNoWriMo (Mês Nacional de Escrita de Novela).",
  "2023-10-12": "Celebre o Dia das Crianças com promoções e descontos em produtos de papelaria para o público infantil.",
  "2023-10-13": "Promova um workshop sobre técnicas modernas de caligrafia e lettering.",
  "2023-10-14": "Lance uma campanha de volta às aulas de verão com descontos em produtos essenciais.",
  "2023-10-15": "Ofereça frete grátis para compras acima de um valor determinado por tempo limitado.",
  "2023-10-16": "Promova uma venda de produtos temáticos de outono, destacando cores e designs sazonais.",
  "2023-10-17": "Lance um concurso de histórias ou poesias com temas de Halloween e outono.",
  "2023-10-18": "Organize um webinar sobre técnicas de organização e planejamento para o final do ano.",
  "2023-10-19": "Destaque produtos ecológicos e sustentáveis, promovendo a consciência ambiental.",
  "2023-10-20": "Realize uma venda de fim de semana focada em produtos para artes gráficas.",
  "2023-10-21": "Lance kits DIY (Faça Você Mesmo) temáticos para o Halloween.",
  "2023-10-22": "Promova um desconto em produtos de papelaria voltados para festas e celebrações.",
  "2023-10-23": "Destaque produtos inovadores que foram lançados recentemente.",
  "2023-10-24": "Ofereça um brinde temático de Halloween nas compras acima de um valor determinado.",
  "2023-10-25": "Realize um concurso de fantasias nas redes sociais com prêmios em produtos.",
  "2023-10-26": "Lance uma promoção 'Compre um e Leve o Segundo pela Metade do Preço' em itens selecionados.",
  "2023-10-27": "Organize um evento de craft night, onde os clientes podem aprender a fazer decorações de Halloween.",
  "2023-10-28": "Promova uma venda-relâmpago em produtos temáticos para o Dia das Bruxas.",
  "2023-10-29": "Ofereça descontos em itens de escrita, como canetas, lápis e marcadores.",
  "2023-10-30": "Lance uma última venda de Halloween, com descontos em produtos temáticos.",
  "2023-10-31": "Celebre o Halloween oferecendo promoções especiais e descontos em toda a loja. E agradeça aos clientes por um mês incrível com um cupom de desconto válido para sua próxima compra.",
};

export const dailyTasksNovembro: IDailyProps = {
  "2023-11-01": "Comece novembro promovendo produtos voltados para o planejamento e organização do final de ano.",
  "2023-11-02": "Celebre o Dia de Finados com uma homenagem nas redes sociais. Pode ser uma boa oportunidade para promover produtos relacionados à escrita reflexiva ou diários de memória.",
  "2023-11-03": "Lance uma nova coleção de produtos temáticos para o Natal.",
  "2023-11-04": "Realize um workshop sobre técnicas de escrita criativa, perfeito para pessoas que desejam começar a escrever cartões e mensagens festivas.",
  "2023-11-05": "Promova uma venda de produtos voltados para a arte, como tintas, pincéis e cadernos de esboço.",
  "2023-11-06": "Lance uma promoção focada em itens de papelaria voltados para presentes.",
  "2023-11-07": "Organize um evento com foco em DIY (Faça Você Mesmo) para decorações festivas.",
  "2023-11-08": "Destaque itens de papelaria que são sustentáveis ou ecológicos, promovendo uma abordagem mais verde para o feriado.",
  "2023-11-09": "Inicie uma série de posts nas redes sociais destacando ideias de presentes para diferentes grupos: professores, colegas de trabalho, amigos etc.",
  "2023-11-10": "Lance um desafio de organização, incentivando as pessoas a se prepararem para o final de ano.",
  "2023-11-11": "Ofereça uma promoção especial para o Dia dos Solteiros. Pode ser uma boa oportunidade para promover produtos focados no autocuidado e desenvolvimento pessoal.",
  "2023-11-12": "Promova uma venda-relâmpago com descontos em produtos populares.",
  "2023-11-13": "Realize um evento online dando dicas sobre como personalizar e decorar agendas e planners para o próximo ano.",
  "2023-11-14": "Lance kits de presente personalizados, permitindo que os clientes escolham itens específicos para criar o presente perfeito.",
  "2023-11-15": "Comemore a Proclamação da República com promoções especiais e destaque produtos relacionados ao Brasil.",
  "2023-11-16": "Ofereça oficinas sobre embrulho de presentes, ensinando técnicas especiais e criativas.",
  "2023-11-17": "Promova uma venda de fim de semana com descontos em produtos de papelaria essenciais.",
  "2023-11-18": "Destaque produtos que ajudam no planejamento financeiro, especialmente considerando as compras de fim de ano.",
  "2023-11-19": "Incentive os clientes a começarem a comprar presentes de Natal agora, evitando a correria de última hora.",
  "2023-11-20": "Lance uma promoção 'Compre um e Leve o Segundo pela Metade do Preço' em itens selecionados.",
  "2023-11-21": "Promova uma noite de compras especial com horário estendido e descontos exclusivos.",
  "2023-11-22": "Lance uma linha especial de cartões de agradecimento, incentivando a gratidão durante esta temporada festiva.",
  "2023-11-23": "Realize um sorteio com a chance de ganhar produtos populares ou um voucher de compras para a loja.",
  "2023-11-24": "Ofereça frete grátis para todas as compras como uma promoção de Black Friday.",
  "2023-11-25": "Continue as promoções de Black Friday, talvez com ofertas diferentes ou especiais que mudam a cada hora.",
  "2023-11-26": "Promova o 'Small Business Saturday', incentivando os clientes a apoiar pequenas empresas locais.",
  "2023-11-27": "Ofereça promoções especiais para a Cyber Monday, com foco em produtos exclusivos online.",
  "2023-11-28": "Realize um webinar sobre planejamento e organização para o próximo ano.",
  "2023-11-29": "Lance um desafio de 30 dias de gratidão nas redes sociais, incentivando os seguidores a compartilhar diariamente algo pelo qual são gratos.",
  "2023-11-30": "Encerre novembro agradecendo aos seus clientes por um mês maravilhoso e ofereça um teaser do que esperar em dezembro.",
};

export const dailyTasksDezembro: IDailyProps = {
  "2023-12-01": "Inicie dezembro com uma grande venda de Natal, destacando novos produtos e best-sellers.",
  "2023-12-02": "Promova um workshop de DIY sobre decorações de Natal feitas à mão.",
  "2023-12-03": "Lance uma promoção '12 dias de descontos', com uma oferta especial a cada dia.",
  "2023-12-04": "Promova uma venda relâmpago de produtos temáticos de Hanukkah.",
  "2023-12-05": "Ofereça embrulho de presente gratuito com qualquer compra.",
  "2023-12-06": "Destaque produtos perfeitos para trocas de presentes no escritório ou festas de amigos secretos.",
  "2023-12-07": "Lance um concurso nas redes sociais onde os clientes podem ganhar um prêmio ao mostrar como estão usando seus produtos durante a temporada de festas.",
  "2023-12-08": "Celebre o Dia da Família promovendo produtos que podem ser desfrutados por todos, como jogos ou kits de artesanato.",
  "2023-12-09": "Realize um evento especial para clientes VIP com descontos exclusivos e acesso antecipado a novos produtos.",
  "2023-12-10": "Ofereça uma promoção onde os clientes recebem um brinde nas compras acima de um determinado valor.",
  "2023-12-11": "Realize um workshop sobre a criação de cartões de Natal personalizados.",
  "2023-12-12": "Promova uma venda 'Compre um, Dê um', onde os clientes podem comprar um produto e doar outro para uma instituição de caridade.",
  "2023-12-13": "Dê destaque aos produtos mais desejados da temporada com descontos especiais.",
  "2023-12-14": "Ofereça frete expresso gratuito para garantir a entrega antes do Natal.",
  "2023-12-15": "Realize um evento de apreciação ao cliente com refrescos, música e descontos na loja.",
  "2023-12-16": "Promova os últimos produtos restantes da sua promoção '12 dias de descontos'.",
  "2023-12-17": "Ofereça descontos em produtos perfeitos para presentes de última hora.",
  "2023-12-18": "Garanta que todos os pedidos online sejam enviados a tempo para o Natal.",
  "2023-12-19": "Promova uma venda de acessórios de inverno, como cadernos e canetas temáticos.",
  "2023-12-20": "Lance um desafio nas redes sociais para os clientes compartilharem suas configurações festivas usando seus produtos.",
  "2023-12-21": "Realize uma venda relâmpago focada em planners e produtos de organização para o novo ano.",
  "2023-12-22": "Dê aos clientes uma prévia dos produtos e promoções que você está planejando para o próximo ano.",
  "2023-12-23": "Ofereça uma promoção especial para aqueles que fizerem compras de última hora na véspera da véspera de Natal.",
  "2023-12-24": "Agradeça aos seus clientes por um ano maravilhoso e deseje-lhes um Feliz Natal.",
  "2023-12-25": "Celebre o Dia de Natal reconhecendo e agradecendo à sua comunidade. Talvez ofereça um código de desconto especial válido para o próximo ano.",
  "2023-12-26": "Lance as promoções de pós-Natal, dando aos clientes ofertas em produtos restantes da temporada festiva.",
  "2023-12-27": "Promova uma venda de fim de ano, preparando os clientes para as festividades do Ano Novo.",
  "2023-12-28": "Destaque produtos de planejamento e resoluções, como diários, planners e kits de metas.",
  "2023-12-29": "Ofereça um workshop online sobre como se preparar e se organizar para o próximo ano.",
  "2023-12-30": "Lance uma venda 'Adeus, 2023!' com descontos em itens selecionados.",
  "2023-12-31": "Agradeça aos seus clientes por um ano incrível e deseje-lhes um próspero Ano Novo!",
};
